# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9b14744b76b450503e0ded22fddb1d60940125db4580a368d13026d0b4e4eb75dba799bb59e90b41569d9e76be5a02e2f13adc4c85dae986532895f4af1c15

test:
  secret_key_base: 3ff387ec7afdc15303faea784606993554fceb4408b31bc6550f4f0d632c33b1248744d4531c06347b25c882dc8b23797681fbac720aa039dd637b071568e4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
